#!/bin/python3
from collections import defaultdict, deque
import math
import os
import random
import re
import sys

# Complete the freqQuery function below.
def freqQuery(queries):
    d = defaultdict(int)
    f = defaultdict(int)
    u = []
    for i in range(len(queries)):
        n = queries[i][1] 
        if queries[i][0] == 1:
            if n in d:
                f[d[n]] -= 1
            d[n] += 1
            f[d[n]] += 1
        elif queries[i][0] == 2:
            if n in d and f[d[n]] > 0:
                if d[n] - 1 in f:
                    v = d[n] - 1
                    f[v] += 1
                f[d[n]] -= 1
                d[n] -= 1           
        else:
            if f[n] > 0:
                u.append(1)
            else:
                u.append(0)
    return u 

        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    queries = []

    for _ in range(q):
        queries.append(list(map(int, input().rstrip().split())))

    ans = freqQuery(queries)

    fptr.write('\n'.join(map(str, ans)))
    fptr.write('\n')

    fptr.close()
