#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter

# Complete the twoStrings function below.
def twoStrings(s1, s2):
    d = len(Counter(s1) - Counter(s2)) != len(Counter (s1)) #si la longitud es diferente será YES, por lo tanto habrá match
    e = len(Counter(s2) - Counter(s1)) != len(Counter (s2)) #si la longitud es la misma será NO, por lo tanto NO habrá match
    if d or e:
        return "YES"
    else: 
        return "NO"

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        s1 = input()

        s2 = input()

        result = twoStrings(s1, s2)

        fptr.write(result + '\n')

    fptr.close()
