#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter

# Complete the twoStrings function below.
def twoStrings(s1, s2):
    d = {}
    for i in s1:                   #Añadir strings al diccionario
        if i in d:
            d[i] += 1
        else:
            d[i] = 1                  
    for j in s2:                
        if j in d:                #Si el string se encuentra en S2, retornar YES
            return "YES"
    return "NO"

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        s1 = input()

        s2 = input()

        result = twoStrings(s1, s2)

        fptr.write(result + '\n')

    fptr.close()
